---
# https://github.com/github/orchestrator

- name: add orchestrator repository
  yum_repository:
    name: github_orchestrator
    description: Github orchestrator repo
    baseurl: https://packagecloud.io/github/orchestrator/el/$releasever/$basearch

- name: install orchestrator
  yum:
    name: "{{ item }}"
  with_items:
    - orchestrator

- name: setup virtual ip moving
  when: mysql_repl_virtual_ip | ipaddr
  tags: virtual_ip
  block:
    - name: add ssh key for root user
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa_orchestrator
        ssh_key_comment: "{{ mysql_orch_user }}@{{ ansible_fqdn }}"
      register: user

    - name: add public key to mysql servers
      authorized_key:
        user: root
        key: "{{ user.ssh_public_key }}"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['mysql'] }}"

- name: open firewall
  firewalld:
    port: "{{ mysql_orch_port }}/tcp"
    state: enabled
    permanent: true
    immediate: yes
