---

- hosts:
    - mysql
    - mysql-proxy
    - mysql-orchestrator
  become: yes
  roles:
    - { role: ntp, tags: ['ntp'] }

- hosts: mysql
  become: yes
  any_errors_fatal: yes
  roles:
    - { role: mysql, tags: ['mysql'] }

- hosts: mysql-proxy
  become: yes
  roles:
    - { role: mysql-proxysql, tags: ['proxysql'] }

- hosts: mysql-orchestrator
  become: yes
  roles:
    - { role: mysql-orchestrator, tags: ['orchestrator'] }

- hosts: mysql
  become: yes
  roles:
    - { role: mysql-test, tags: ['test'] }
