---

mysql_test_db: 'mysql_test'

mysql_test_table: 'test'

mysql_test_user:
  username: mysql_test
  password: mysql_test
  grants: "{{ mysql_test_db }}.*:ALL"

mysql_proxy_host:
  "{{ hostvars[groups['mysql-proxy'][0]].ansible_default_ipv4.address if groups['mysql-proxy'] is defined else '' }}"

mysql_proxy_port: 3306
